I4G003937BGM/I4G003937BGM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("api/links/", include("links.urls"))
]

I4G003937BGM/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post"),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path("delete/<slug:slug>", views.PostDeleteView.as_view(), name="post_delete"),
    path("update/<slug:slug>", views.PostUpdateView.as_view(), name="post_update"),
    path("read/<slug:slug>", views.PostDetailView.as_view(), name="post_detail"),

]

I4G003937BGM/links/urls.py
from django.urls import path
from . import views

app_name="link"

urlpatterns = [
    path("create/", views.PostCreateApi.as_view(), name="api_create"),
    path("update/<int:pk>", views.PostUpdateApi.as_view(), name="api_update"),
    path("delete/<int:pk>", views.PostDeleteApi.as_view(), name="api_delete"),
    path("", views.PostListApi.as_view(), name="api_list"),
]

I4G003937BGM/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.


class Post(models.Model):

    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published")
    )

    # DB Fields
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=300, unique=True, editable=False)
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField(default="")

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft"
    )

    class Meta:
        ordering = ("-publish",)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        pass 

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})
    

I4G003937BGM/links/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.

class Link(models.Model):
    target_url = models.URLField(max_length=200)
    description = models.CharField(max_length=200)
    identifier = models.SlugField(null=True, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.target_url

I4G003937BGM/blog/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from .models import Post

class PostListView(ListView):
    model: Post
    template_name = 'home.html'
    def get_queryset(self):
        """Return Post """
        return Post.objects.order_by('title')[:5]
    
    
class PostCreateView(CreateView):
    model = Post
    fields = "__all__"
    template_name = 'home.html'
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog.html'
    
class PostUpdateView(UpdateView):
    model = Post
    fields = "__all__"
    template_name = 'home.html'
    
class PostDeleteView(UpdateView):
    model = Post
    fields = "__all__"
    template_name = 'home.html'

I4G003937BGM/links/views.py
from rest_framework import generics, serializers
from .models import Link
# Create your views here.
from .serializers import LinkSerializer


class PostListApi(generics.ListAPIView):
    queryset = Link.objects.filter(active=True)
    serializer_class = LinkSerializer


class PostCreateApi(generics.CreateAPIView):
    queryset = Link.objects.filter(active=True)
    serializer_class = LinkSerializer


class PostDetailApi(generics.RetrieveAPIView):
    queryset = Link.objects.filter(active=True)
    serializer_class = LinkSerializer


class PostUpdateApi(generics.UpdateAPIView):
    queryset = Link.objects.filter(active=True)
    serializer_class = LinkSerializer


class PostDeleteApi(generics.DestroyAPIView):
    queryset = Link.objects.filter(active=True)
    serializer_class = LinkSerializer

I4G003937BGM/blog/templates/home.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | My Blog ✏</title> 
    {% else %}
        <title>My Blog Posts 📝</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">DJANGO C.R.U.D.</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'blog:post' %}">Posts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="https://zuri.team/" target="_blank">Checkout Zuri</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

I4G003937BGM/templates/home.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | My Blog ✏</title> 
    {% else %}
        <title>My Blog Posts 📝</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">DJANGO C.R.U.D.</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'blog:all' %}">Posts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="https://zuri.team/" target="_blank">Checkout Zuri</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>